---
# tasks file for user_master_export

 - name: Fetch pc3_val and ctc_val
   sap_function_call:
     user_master_export:
       sid_ctc_val: True
   register: pc3_ctc_val
   tags: ctc


 - debug: var=pc3_ctc_val.meta.stdout
   tags: ctc

 - name: Copy Variables templates containing variant details
   template:
        src: variant_data.py.j2
        dest: "{{ playbook_dir }}/module_utils/user_master_export.py"
        force: yes
   vars:
     pc3_val: "{{ pc3_ctc_val.meta.stdout.sid_val }}"
     ctc_val: "{{ pc3_ctc_val.meta.stdout.ctc_val }}"
   tags: ctc

 - name: Check Variant
   variant:
       report: "{{ report }}"
       variant_name: "{{ variant_name }}"
       action: check
   register: var_check

 - name: Delete Variant if already exists
   variant:
       report: "{{ report }}"
       variant_name: "{{ variant_name }}"
       action: delete
   when: var_check.stdout == "True"

 - name: Create Variant
   variant:
       report: "{{ report }}"
       variant_name: "{{ variant_name }}"
       action: create
   when: var_check.stdout == "False"

 - name: User Master Export
   sap_function_call:
     user_master_export:
       sid_ctc_val: False
       report: "{{ report }}"
       variant_name: "{{ variant_name }}"
   register: user_master_export

 - debug: var=user_master_export

 - name: Waiting for user master export to complete
   pause:
     seconds: 10

 - name: Delete Variant
   variant:
       report: "{{ report }}"
       variant_name: "{{ variant_name }}"
       action: delete

