---
# tasks file for user_master_export
 - name: Copy Variables templates containing variant details
   template:
        src: variant_data.py.j2
        dest: "{{playbook_dir}}/module_utils/variant_data.py"
        force: yes

 - name: Check Variant
   variant:
       report: "{{ report }}"
       variant_name: "{{ variant_name }}"
       action: check
   register: var_check

 - name: Create Variant
   variant:
       report: "{{ report }}"
       variant_name: "{{ variant_name }}"
       action: create
   when: var_check.stdout == "False"

 - name: Delete TRC Queues SM58
   sap_function_call:
     SUBST_START_REPORT_IN_BATCH:
         IV_JOBNAME: "DELETE_TRC_QUEUES_SM58"
         IV_REPNAME: "{{ report }}"
         IV_VARNAME: "{{ variant_name }}"
   register: del_TRC_SM58

 - debug: var=del_TRC_SM58

 - name: Waiting for the above task to delete old background jobs
   pause:
     seconds: 10

 - name: Delete Variant
   variant:
       report: "{{ report }}"
       variant_name: "{{ variant_name }}"
       action: delete
