---
# tasks file for user_master_export
  - name: Fetch sys_params (client, sid, bin_path, trans_val, sid_ctc_val)
    sap_function_call:
      FETCH: sys_params
    register: sys_params

  - name: Copy Variables templates containing variant details
    template:
      src: variant_data.py.j2
      dest: "{{playbook_dir}}/module_utils/variant_data.py"
      force: yes
    vars:
      client: "{{ sys_params.meta.stdout.client }}"

  - name: Check Variant
    variant:
      report: "{{ report }}"
      variant_name: "{{ variant_name }}"
      action: check
    register: var_check

  - name: Delete Variant if already exists
    variant:
      report: "{{ report }}"
      variant_name: "{{ variant_name }}"
      action: delete
    when: var_check.meta.stdout == True

  - name: Create Variant
    variant:
      report: "{{ report }}"
      variant_name: "{{ variant_name }}"
      action: create
    register: var_create

  - name: Export printer devices
    sap_function_call:
      SUBST_START_REPORT_IN_BATCH:
        IV_JOBNAME: "{{ report }}"
        IV_REPNAME: "{{ report }}"
        IV_VARNAME: "{{ variant_name }}"
    register: export_printers
    when: var_create.meta.stdout == True

  - debug: var=export_printers

  - name: Waiting for exporint printer devices
    pause:
      seconds: 10

  - name: Delete Variant
    variant:
      report: "{{ report }}"
      variant_name: "{{ variant_name }}"
      action: delete
