---
# tasks file for setup-vars
 - name: Create $HOME/.config directory if doesn't exist
   file:
     path: "{{ ansible_env.HOME }}/.config"
     state: directory
     mode: '0755'
 
 - name: Delete existing sap_config.ini configuration file
   file:
     dest: "{{ ansible_env.HOME }}/.config/sap_config.ini"
     state: absent

 - name: Create configuration file sap_config.ini in $HOME/.config/
   template:
     src: sap_config.ini
     dest: "{{ ansible_env.HOME }}/.config/sap_config.ini"
     force: yes

 - name: Adding an entry in /etc/hosts
   win_hosts:
     state: present
     canonical_name: "{{ lookup('ini', 'ashost section=SAP file={{ ansible_env.HOME }}/.config/sap_config.ini') }}"
     ip_address: "{{ lookup('ini', 'target_ip_addr section=SAP file={{ ansible_env.HOME }}/.config/sap_config.ini') }}"
   when: ansible_facts['distribution'] == "Windows"
   tags: hostupdate

 - name: Adding an entry in /etc/hosts
   lineinfile:
     dest: /etc/hosts
     insertafter: EOF
     line: "{{ lookup('ini', 'target_ip_addr section=SAP file={{ ansible_env.HOME }}/.config/sap_config.ini') }}\t{{ lookup('ini', 'ashost section=SAP file={{ ansible_env.HOME }}/.config/sap_config.ini') }}"
     state: present
   when: ansible_facts['distribution'] != "Windows"
   become: yes
   tags: hostupdate

 - name: updating hosts file for export/import system tables
   template:
     src: hosts
     dest: "{{ item }}"
     force: yes
   with_items:
      - "{{ playbook_dir }}/../step3-Export_sys_tables/hosts"
      - "{{ playbook_dir }}/../../post-Refresh/step04-Import_sys_tables/hosts"
      - "{{ playbook_dir }}/hosts"

 - name: Check connection
   command: "{{ ansible_python_interpreter }} {{ playbook_dir }}/connection.py"
   register: conn

 - debug:
     msg: "Connection is Successful"
   when: conn.stdout == "True"

 - debug:
     msg: "Failed to establish connection to SAP: {{ conn.stdout_lines }}"
   when: conn.stdout != "True"



