---
# tasks file for system_user_lock

 - name: Fetch entire system user list
   sap_function_call:
     BAPI_USER_LOCK:
       fetch: users
   register: users

 - debug: var=users

 - name: Lock Users
   sap_function_call:
     BAPI_USER_LOCK:
       lock_users:
         exception_list: "{{ exception_list }}"
         action: lock
   register: lock

 - debug: var=lock

 - name: Unlock Users
   sap_function_call:
     BAPI_USER_LOCK:
       lock_users:
         exception_list: ['SAP*']
         action: unlock
   register: unlock

 - debug: var=unlock


