---
# tasks file for copy_exp_ctl
  - name: copy exp.ctl file
    win_template:
      src: import.ctl
      dest: "{{ ansible_env.TEMP }}\import.ctl"
      group: sapsys
      owner: "{{ lookup('ini', 'sid section=SAP file={{ config_file_path }}')|lower }}adm"
      force: yes
    become: yes
