- hosts: localhost
  vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: system_user_lock
      vars:
        exception_list: "{{ lookup('ini', 'exception_list section=SAP file={{ ansible_env.HOME }}/.config/sap_config.ini') }}"