---
# tasks file for copy_exp_ctl
  - name: copy exp.ctl file
    template:
      src: import.ctl
      dest: /tmp/import.ctl
      group: sapsys
      owner: "{{ lookup('ini', 'sid section=SAP file={{ ansible_env.HOME }}/.config/sap_config.ini')|lower }}adm"
      force: yes
    become: yes
