---
# tasks file for system_user_lock

 - name: Fetch entire system user list
   sap_function_call:
     FETCH: sys_users
   register: users

 - debug: var=users

 - name: Fetch existing administer locked users
   sap_function_call:
     FETCH: sys_locked_users
   register: locked_users

 - debug: var=locked_users

 - name: Lock Users
   sap_function_call:
     BAPI_USER_LOCK:
       EXCEPTION_USERS: "{{ exception_list }}"
   register: lock

 - debug: var=lock

 - name: Unlock Users
   sap_function_call:
     BAPI_USER_UNLOCK:
       EXCEPTION_USERS: "['SAP*']"
   register: lock

 - debug: var=lock

# - name: Fetch entire system user list
#   sap_function_call:
#     BAPI_USER_LOCK:
#       fetch: users
#   register: users
#
# - debug: var=users
#
# - name: Fetch existing Administer locked user list
#   sap_function_call:
#     BAPI_USER_LOCK:
#       fetch: locked_users
#   register: locked_users
#
# - debug: var=locked_users
#
# - name: Lock Users
#   sap_function_call:
#     BAPI_USER_LOCK:
#       lock_users:
#         exception_list: "{{ exception_list }}"
#         action: lock
#   register: lock
#
# - debug: var=lock
#
## - name: Unlock Users
##   sap_function_call:
##     BAPI_USER_LOCK:
##       lock_users:
##         exception_list: "{{ exception_list }}"
##         action: unlock
##   register: unlock
##
## - debug: var=unlock
#
#
