---
# tasks file for system_user_lock
 - name: Create sap_config.cnf file in $HOME/.config/sap_config.cnf
   template:
     src: sap_config.cnf
     dest: "{{ ansible_env.HOME }}/.config/sap_config.ini"
     force: yes
