---
# tasks file for export_system_tables
  - name: Insert Command
    sap_function_call:
      ZSXPG_COMMAND_INSERT:
        NAME: 'ZTABEXP'
        OPSYSTEM: 'Linux'
        OPCOMMAND: 'R3trans'
        PARAMETERS: '-w /tmp/exp_ecc.log /tmp/exp.ctl'
    register: comm_insert
    ignore_errors: yes

  - name: Insert Command
    sap_function_call:
      ZSXPG_COMMAND_INSERT:
        NAME: 'ZTABEXP'
        OPSYSTEM: 'Linux'
        OPCOMMAND: 'R3trans'
        PARAMETERS: "-w {{ ansible_env.TEMP }}\exp_ecc.log {{ ansible_env.TEMP }}\exp.ctl"
    register: comm_insert
    ignore_errors: yes

  - debug: var=comm_insert

  - name: Execute Command
    sap_function_call:
      SXPG_COMMAND_EXECUTE:
        NAME: "ZTABEXP"
    register: comm_execute

  - debug: var=comm_execute