---
# tasks file for system_user_lock
 - name: Fetch entire system user list
   sap_function_call:
     FETCH: sys_users
   register: users

 - debug: var=users

 - name: Lock Users
   sap_function_call:
     BAPI_USER_LOCK:
       EXCEPTION_USERS: "{{ lookup('ini', 'exception_list section=SAP file={{ config_file_path }}') }}"
       ALL_USERS: "{{ users.meta.USERS }}"
   register: lock

 - debug: var=lock
