---
# tasks file for user_master_export

 - name: Check background Jobs
   sap_function_call:
      TH_WPINFO:
         fetch: bgd_val
   register: bgd_val

 - debug:
     msg: "Background work process is configured properly"
   when: bgd_val.meta.result == True

 - name: Custom check to throw error based on BGD value.
   fail:
     msg: "Background work process is not set. Please change parameter value rdisp rdisp/wp_no_btc not equal to 0."
   when: bgd_val.meta.result == False
