---
# tasks file for user_master_export
 - name: Copy Variables templates containing variant details
   template:
        src: variant_data.py.j2
        dest: "{{playbook_dir}}/module_utils/variant_data.py"
        force: yes

 - name: Check Variant
   variant:
       report: "{{ report }}"
       variant_name: "{{ variant_name }}"
       action: check
   register: var_check

 - name: Create Variant
   variant:
       report: "{{ report }}"
       variant_name: "{{ variant_name }}"
       action: create
   when: var_check.stdout == "False"

 - name: Delete old background Jobs
   sap_function_call:
     del_old_bg_jobs:
         report: "{{ report }}"
         variant_name: "{{ variant_name }}"
   register: del_old_bg_jobs

 - debug: var=del_old_bg_jobs

 - name: Waiting for the above task to delete old background jobs
   pause:
     seconds: 10

 - name: Delete Variant
   variant:
       report: "{{ report }}"
       variant_name: "{{ variant_name }}"
       action: delete
