---
# tasks file for import_system_tables
  - name: Insert Command
    sap_function_call:
      ZSXPG_COMMAND_INSERT:
        NAME: 'ZTABIMP'
        OPSYSTEM: 'Linux'
        OPCOMMAND: 'R3trans'
        PARAMETERS: '-w /tmp/import_ecc.log /tmp/import.ctl'
    register: comm_insert
    tags: linux

  - name: Insert Command
    sap_function_call:
      ZSXPG_COMMAND_INSERT:
        NAME: 'ZTABIMP'
        OPSYSTEM: 'Linux'
        OPCOMMAND: 'R3trans'
        PARAMETERS: '-w {{ ansible_env.TEMP }}/import_ecc.log {{ ansible_env.TEMP }}/import.ctl'
    register: comm_insert
    tags: windows

  - debug: var=comm_insert

  - name: Execute Command
    sap_function_call:
      SXPG_COMMAND_EXECUTE:
        NAME: "ZTABIMP"
    register: comm_execute
    tags:
      - windows
      - linux

  - debug: var=comm_execute