---
# tasks file for user_master_export
  - name: Insert Command
    sap_function_call:
      ZSXPG_COMMAND_INSERT:
        NAME: 'ZTABEXP'
        OPSYSTEM: 'Linux'
        OPCOMMAND: 'R3trans'
        PARAMETERS: '-w /tmp/exp_ecc.log /tmp/exp.ctl'
    register: comm_insert

  - debug: var=comm_insert


