---
# tasks file for system_user_lock
 - name: Unlock Users
   sap_function_call:
     BAPI_USER_UNLOCK:
       EXCEPTION_USERS: "{{lookup('file', '/tmp/existing_locked_users')}}"
   register: lock

 - debug: var=lock

