---
# tasks file for user_master_export

 - name: Check background Jobs
   sap_function_call:
      TH_WPINFO:
         fetch: bgd_val
   register: bgd_val

 - debug:
     msg: "No BGD Entry found!"
   when: bgd_val.meta.result == False

 - name: Custom check to throw error based on BGD value.
   fail:
     msg: "Background work process is not set to 0. Please change it immediately"
   when: bgd_val.meta.result == True
