---
# tasks file for system_user_lock
 - name: System User Lock
   sap_function_call:
        bapi_user_lock:
            user_list: True
            existing_locked_users: True
            lock_users:
                action: lock
   register: system_user_lock

 - debug: var=system_user_lock

 - name: System User UnLock
   sap_function_call:
        bapi_user_lock:
            user_list: True
            existing_locked_users: False
            lock_users:
                action: unlock
   register: system_user_unlock

 - debug: var=system_user_unlock
