---
# tasks file for system_user_lock

 - name: Fetch User list
   sap_function_call:
     bapi_user_lock:
       fetch: users
   register: users

 - debug: var=users

 - name: Fetch User list
   sap_function_call:
     bapi_user_lock:
       fetch: locked_users
   register: locked_users

 - debug: var=locked_users

 - name: Lock Users
   sap_function_call:
     bapi_user_lock:
       lock_users:
         exception_list: ['SST_TRNG', 'KRISHNA', 'BJOERN', 'DDIC', 'SMAGENDIRAN', 'GIRIDR', 'MRAM']
         action: lock
   register: lock

 - debug: var=lock