---
# tasks file for system_user_lock

 - name: Fetch User list
   sap_function_call:
     bapi_user_lock:
       fetch: users
   register: users

 - debug: var=users

 - name: System User Lock
   sap_function_call:
        bapi_user_lock:
            user_list: True
            existing_locked_users: True
            lock_users:
                action: lock
                exception_list: ['SST_TRNG', 'KRISHNA', 'BJOERN', 'DDIC', 'SMAGENDIRAN', 'GIRIDR', 'MRAM']
   register: system_user_lock
   tags: lock

 - debug: var=system_user_lock

 - name: System User UnLock
   sap_function_call:
        bapi_user_lock:
            user_list: True
            existing_locked_users: False
            lock_users:
                action: unlock
                exception_list: ['SAP*']
   register: system_user_unlock
   tags: unlock

 - debug: var=system_user_unlock
