---
# tasks file for system_user_lock
 - name: Fetch user list
   function_module:
     user_list:
       action: True
   register: user_list

 - debug: var=user_list

 - name: Fetch locked user list
   function_module:
     existing_locked_users:
       action: True

 - debug: True