- hosts: all
  vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: logical_system_conversion
      vars:
        report: "STC_SC_UI_BDLS"
        variant_name: "Z_PRDTOQA"
        source_client: "{{ source_sap_client }}"
        source_sid: "{{ source_sap_sid }}"
        client: "{{ target_sap_client }}"
        sid: "{{ target_sap_sid }}"
