---
# tasks file for backup_restore
  - name: copy systemdb_restore.sh
    template:
      src: systemdb_restore.sh
      dest: /tmp/systemdb_restore.sh
      group: sapsys
      owner: "{{ lookup('ini', 'database_sid section=SAP file={{ config_file_path }} ')|lower }}adm"
      force: yes
    become: yes

  - name: copy tenantdb_restore.sh
    template:
      src: tenantdb_restore.sh
      dest: /tmp/tenantdb_restore.sh
      group: sapsys
      owner: "{{ lookup('ini', 'database_sid section=SAP file={{ config_file_path }} ')|lower }}adm"
      force: yes
    become: yes

  - name: copy stopsap.sh
    template:
      src: stopsap.sh
      dest: /tmp/stopsap.sh
    mode: u=rwx,g=rx,o=rx

  - name: Stop sap application
    command: /tmp/stopsap.sh
    become: yes
    become_user: "{{ lookup('ini', 'sid section=SAP file={{ config_file_path }} ')|lower }}adm"

  - name: Waiting for sap application to shut down
    pause:
      seconds: 120

  - name: Run systemdb backup script
    command: /tmp/systemdb_restore.sh
    become: yes
    become_user: "{{ lookup('ini', 'database_sid section=SAP file={{ config_file_path }} ')|lower }}adm"
    mode: u=rwx,g=rx,o=rx

  - name: Run tenantdb backup script
    command: /tmp/tenantdb_restore.sh
    become: yes
    become_user: "{{ lookup('ini', 'database_sid section=SAP file={{ config_file_path }} ')|lower }}adm"
    mode: u=rwx,g=rx,o=rx