---
# tasks file for copy_exp_ctl
  - name: copy exp.ctl file
    template:
      src: exp.ctl
      dest: /tmp/exp.ctl
      group: sapsys
      owner: "{{ sid|lower }}adm"
      force: yes
    become: yes
